package summary

import (
	"context"
	"fmt"
	"os"
	"time"

	"bot/pkg/logger"

	"google.golang.org/genai"
)

// Package logger
var log = logger.Package("summary")

type Summarizer struct {
	client *genai.Client
}

type Config struct {
	APIKey string
}

type modelEntry struct {
	name        string
	useThinking bool
}

// Models in order of preference
var modelPriority = []modelEntry{
	{name: "gemini-3.1-flash-lite-preview", useThinking: true},
	{name: "gemini-3.1-flash-lite", useThinking: true},
	{name: "gemini-2.5-flash-lite"},
	{name: "gemini-2.0-flash-lite"},
	{name: "gemini-2.0-flash"},
	{name: "gemini-1.5-flash-8b"},
}

// New creates a new instance of Summarizer
func New(cfg Config) (*Summarizer, error) {
	ctxLog := log.WithContext("method", "New")

	ctx := context.Background()
	ctxLog.Info("Creating Vertex AI client")
	client, err := genai.NewClient(ctx, &genai.ClientConfig{
		APIKey:  cfg.APIKey,
		Backend: genai.BackendVertexAI,
	})
	if err != nil {
		ctxLog.Error("Error creating Vertex AI client", "error", err)
		return nil, fmt.Errorf("error creating Vertex AI client: %w", err)
	}

	ctxLog.Info("Summarizer initialized successfully")
	return &Summarizer{
		client: client,
	}, nil
}

// Close closes the client
func (s *Summarizer) Close() {
	ctxLog := log.WithContext("method", "Close")
	ctxLog.Info("Client cleanup (no action needed)")
}

// GenerateSummary generates a summary for the given PDF file
// with fallback to alternative models if the primary model fails
func (s *Summarizer) GenerateSummary(ctx context.Context, pdfPath string) (string, error) {
	ctxLog := log.WithRequestContext(ctx).
		WithContext("method", "GenerateSummary").
		WithContext("pdfPath", pdfPath)

	ctxLog.Debug("Reading PDF file")
	pdfData, err := os.ReadFile(pdfPath)
	if err != nil {
		ctxLog.Error("Error reading PDF file", "error", err)
		return "", fmt.Errorf("error reading PDF file: %w", err)
	}
	ctxLog.Debug("PDF file read successfully", "bytes", len(pdfData))

	// Try each model in order of priority
	var lastError error
	for _, model := range modelPriority {
		ctxLog.Debug("Attempting to generate summary", "model", model.name)
		summary, err := s.tryGenerateSummaryWithModel(ctx, model, pdfData)
		if err == nil {
			// Success with this model
			ctxLog.Info("AI summary generated successfully", "model", model.name, "length", len(summary))
			return summary, nil
		}

		lastError = err
		ctxLog.Warn("Failed to generate summary with model", "model", model.name, "error", err)

		// Add a small delay before trying the next model
		time.Sleep(500 * time.Millisecond)
	}

	ctxLog.Error("All models failed to generate summary", "lastError", lastError)
	return "", fmt.Errorf("all models failed to generate summary, last error: %w", lastError)
}

// tryGenerateSummaryWithModel attempts to generate a summary with the specified model
func (s *Summarizer) tryGenerateSummaryWithModel(ctx context.Context, model modelEntry, pdfData []byte) (string, error) {
	ctxLog := log.WithRequestContext(ctx).
		WithContext("method", "tryGenerateSummaryWithModel").
		WithContext("model", model.name)

	ctxLog.Debug("Creating model config")
	config := createModelConfig(model)

	ctxLog.Debug("Creating chat session with inline PDF")
	// Send PDF as inline data (Vertex AI does not support the Files API)
	history := []*genai.Content{
		{
			Role: genai.RoleUser,
			Parts: []*genai.Part{
				{
					InlineData: &genai.Blob{
						Data:     pdfData,
						MIMEType: "application/pdf",
					},
				},
			},
		},
	}

	chat, err := s.client.Chats.Create(ctx, model.name, config, history)
	if err != nil {
		ctxLog.Error("Error creating chat session", "error", err)
		return "", fmt.Errorf("error creating chat session with model %s: %w", model.name, err)
	}

	ctxLog.Debug("Sending message to model")
	resp, err := chat.Send(ctx, genai.NewPartFromText("Please provide a summary of this document"))
	if err != nil {
		ctxLog.Error("Error generating summary", "error", err)
		return "", fmt.Errorf("error generating summary with model %s: %w", model.name, err)
	}

	if len(resp.Candidates) == 0 || len(resp.Candidates[0].Content.Parts) == 0 {
		ctxLog.Error("No summary generated", "candidates", len(resp.Candidates))
		return "", fmt.Errorf("no summary generated by model %s", model.name)
	}

	// Extract text from the response
	part := resp.Candidates[0].Content.Parts[0]
	if part.Text != "" {
		return part.Text, nil
	}

	return fmt.Sprintf("%v", part), nil
}

// createModelConfig creates the model configuration with optimal settings
func createModelConfig(model modelEntry) *genai.GenerateContentConfig {
	temperature := float32(0.7)
	maxTokens := int32(8192)

	systemInstruction := `You are a concise Formula 1 news bot posting to Threads. Based on the attached FIA document, generate a 40–60 word summary.

First, identify the document type:
- **Stewards Decision**: Summarize the specific penalty, reprimand, or finding. Include the driver/team involved, the infringement, and the outcome. If the stewards investigated but took no further action, state that clearly.
- **Classification / Timing Sheet**: Summarize who topped the session, their time, notable gaps, and total laps completed by the field etc.
- **Technical Directive / Regulation Update**: Summarize the rule change or clarification and which teams or components it affects.
- **Other**: Summarize the key factual content.

Keep the tone neutral and factual. Do not include the document type in the summary. Do not add commentary, speculation, or explanation beyond the summary. Do not use hashtags or emojis.`

	config := &genai.GenerateContentConfig{
		SystemInstruction: genai.NewContentFromText(systemInstruction, genai.RoleUser),
		Temperature:       &temperature,
		MaxOutputTokens:   maxTokens,
	}

	if model.useThinking {
		config.ThinkingConfig = &genai.ThinkingConfig{
			ThinkingLevel: genai.ThinkingLevelMedium,
		}
	}

	return config
}
