FROM --platform=linux/amd64 golang:1.24.5 AS builder

# Install required dependencies for go-fitz
RUN apt-get update && apt-get install -y \
    build-essential \
    pkg-config \
    libmupdf-dev \
    mupdf \
    mupdf-tools

COPY go.mod go.mod
COPY go.sum go.sum
RUN go mod download -x

COPY cmd cmd
COPY pkg pkg

# Enable CGO and build
RUN CGO_ENABLED=1 GOOS=linux go build -o /app ./cmd/svc/main.go

FROM --platform=linux/amd64 debian:stable-slim

WORKDIR /root/

# Install runtime dependencies
RUN apt-get update && apt-get install -y \
    mupdf \
    mupdf-tools \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

COPY --from=builder /app .

# Expose pprof port for profiling
EXPOSE 6060

CMD [ "./app" ]
