FROM --platform=linux/amd64 golang:1.23.0 AS builder

COPY go.mod go.mod
COPY go.sum go.sum
RUN go mod download -x

COPY cmd cmd
COPY pkg pkg

RUN CGO_ENABLED=0 GOOS=linux go build -o /app ./cmd/svc/main.go

FROM --platform=linux/amd64 alpine:latest

WORKDIR /root/

COPY --from=builder /app .
COPY .env .

CMD [ "./app" ]
